### ISSUE TITLE
How to use server console websocket url?

### ISSUE THREAD

**Issue by kosta** [hetznercloud/hcloud-python#119]
`BoundServer.request_console()` returns an object containing a websocket url to connect to and a password.

Is there any documentation on how to use that websocket url? Browsers cannot open it directory; I can connect using `wscat` or `websocat`, but I don't speak fluent websocket, how do I get to a remote console from there?

Thanks in advance!

Cheers,
Kosta

**Comment by LKaemmerling** [comment]
Hey @kosta,

our own implementation for the server console uses https://novnc.com to connect to the given values.

Does this help you :)?

**Comment by kosta** [comment]
Yes, that _almost_ helps. I don't see where I can pass the `wss://` url to either novnc or websockify.

Does this implement a proper VNC connection or just a text-based serial console over secure websockets?

**Comment by LKaemmerling** [comment]
@kosta we basically just gave you the url for a vnc connection. You can pass it to novnc(exactly this is what our cloud console does). I hope this helps you. I will close the issue for now. If you still have questions about this feel free to reopen this issue.

**Comment by c0dev0id** [comment]
I was looking for the same thing. What we actually want is to avoid opening a browser and just type "sometool <url>" enter the pw an be on the console. Just like it works with a regular vnc application.

The wss url is pretty useless for this. There is no cli vnc client that accepts it. Yes, if there is a novnc deployed somewhere, it can work with it. But setting this up entirely defeats to point of the question.

The main reason we use hcloud is because it can be scripted and it works on the CLI. Requiring a big novnc install and a browser to connect to the console is... not great.

There's also no way to get to a serial console as far as I know. So the H web-frontend still the next best thing to use for the initial setup until ssh works.
